import { Outfit, Space_Grotesk, JetBrains_Mono } from "next/font/google"; // Added Space_Grotesk
import "./globals.css";
import CursorSpotlight from "./components/ui/CursorSpotlight";
import GrainOverlay from "./components/ui/GrainOverlay";
import { Metadata } from "next";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({ // Added config
  variable: "--font-heading",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portpolyo ni Emman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${spaceGrotesk.variable} ${jetbrainsMono.variable} antialiased cursor-none`}
      >
        <CursorSpotlight />
        <GrainOverlay />
        {children}
      </body>
    </html>
  );
}
